#!/usr/bin/env python3
"""TIER 1 review report — read-only filtered view of source_triage results.

Filters TIER 1 entries from non-normalized PDFs, computes per-item confidence,
and emits a focused review markdown. NO file I/O on Source Lake (no rename, no
meta.yml, no markdown drafts).

Usage:
    python3 scripts/triage_review.py
"""
from __future__ import annotations

import sys
from collections import Counter
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from lib.triage import is_normalized, triage_one, count_domain_siblings, recommend_mode

PDF_DIR = ROOT / "sources" / "fireblocks" / "pdf"
OUT_MD = ROOT / "tests" / "triage" / "tier1-review.md"


def collect_non_normalized() -> list[str]:
    return sorted(p.name for p in PDF_DIR.glob("*.pdf") if not is_normalized(p.name))


def confidence(domain_kws: list[str], t3_kws: list[str], mode: str) -> str:
    """HIGH / MEDIUM / REVIEW per signal strength."""
    if t3_kws:
        return "REVIEW (TIER 3 keyword overlap)"
    if len(domain_kws) >= 2 and mode == "mode_b_cluster":
        return "HIGH"
    if len(domain_kws) >= 1 and mode == "mode_b_cluster":
        return "HIGH"
    if len(domain_kws) >= 2:
        return "MEDIUM-HIGH"
    if len(domain_kws) == 1 and mode == "mode_b":
        return "MEDIUM (singleton, weak)"
    return "MEDIUM"


def main() -> None:
    iso_date = date.today().isoformat()
    filenames = collect_non_normalized()
    if not filenames:
        print("No non-normalized PDFs.")
        return

    # Full triage (re-compute for keyword detail)
    results = [triage_one(fn, iso_date=iso_date) for fn in filenames]
    domain_counts = count_domain_siblings(results)
    for r in results:
        if r.domain != "unknown":
            sib = domain_counts.get(r.domain, 0) - 1
            r.recommended_mode, r.rationale = recommend_mode(r.tier, sib)

    tier1 = [r for r in results if r.tier == "1"]
    print(f"TIER 1: {len(tier1)} entries")

    # Per-item confidence
    enriched = []
    for r in tier1:
        conf = confidence(r.domain_keywords_matched, r.tier3_keywords_matched, r.recommended_mode)
        enriched.append((r, conf))

    # Sort by (confidence rank, domain, slug)
    conf_rank = {"HIGH": 0, "MEDIUM-HIGH": 1, "MEDIUM": 2, "MEDIUM (singleton, weak)": 3, "REVIEW (TIER 3 keyword overlap)": 4}
    enriched.sort(key=lambda x: (conf_rank.get(x[1], 99), x[0].domain, x[0].proposed_slug))

    # Sample apply candidates = first 10 HIGH
    high = [(r, c) for r, c in enriched if c == "HIGH"][:10]

    # ---- write report ----
    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by scripts/triage_review.py — read-only review, no file ops -->")
    lines.append(f"# TIER 1 Triage Review ({iso_date})")
    lines.append("")
    lines.append(f"**Scope**: TIER 1 candidates from `tests/triage/triage-report.yml` only ({len(tier1)} entries).")
    lines.append("")
    lines.append("**Approval status**: REVIEW ONLY — no rename, no meta.yml, no markdown drafts.")
    lines.append("")
    lines.append("## Distribution")
    lines.append("")
    by_conf = Counter(c for _, c in enriched)
    lines.append("| Confidence | Count |")
    lines.append("|---|---:|")
    for c, n in by_conf.most_common():
        lines.append(f"| {c} | {n} |")
    lines.append("")
    by_domain = Counter(r.domain for r, _ in enriched)
    lines.append("| Domain | Count |")
    lines.append("|---|---:|")
    for d, n in by_domain.most_common():
        lines.append(f"| {d} | {n} |")
    lines.append("")
    by_mode = Counter(r.recommended_mode for r, _ in enriched)
    lines.append("| Recommended Mode | Count |")
    lines.append("|---|---:|")
    for m, n in by_mode.most_common():
        lines.append(f"| `{m}` | {n} |")
    lines.append("")

    # ---- Sample apply candidates ----
    lines.append("## Sample Apply Candidates (Top 10 HIGH confidence)")
    lines.append("")
    lines.append("권장: 우선 본 10건만 `--apply-hygiene` 시도 (samples by hand) → 검증 후 전체 312건 진행 결정.")
    lines.append("")
    lines.append("| # | Domain | Mode | Domain keywords | Proposed slug | Original |")
    lines.append("|---:|---|---|---|---|---|")
    for i, (r, conf) in enumerate(high, 1):
        orig_short = r.original_filename[:55] + ("..." if len(r.original_filename) > 55 else "")
        kws = ", ".join(r.domain_keywords_matched)
        lines.append(
            f"| {i} | {r.domain} | `{r.recommended_mode}` | {kws} | `{r.proposed_slug[:55]}` | {orig_short} |"
        )
    lines.append("")

    # ---- Potential mis-classification ----
    review_needed = [(r, c) for r, c in enriched if "REVIEW" in c]
    if review_needed:
        lines.append("## ★ Potential Mis-classification (TIER 3 keyword overlap)")
        lines.append("")
        lines.append("본 항목들은 TIER 1 으로 분류되었으나 TIER 3 keyword 와 겹침 — 수동 검토 필요.")
        lines.append("")
        lines.append("| Original | Proposed | Domain (matched) | TIER 3 keywords matched | Recommended Mode |")
        lines.append("|---|---|---|---|---|")
        for r, _ in review_needed:
            orig_short = r.original_filename[:50] + ("..." if len(r.original_filename) > 50 else "")
            d_kws = ", ".join(r.domain_keywords_matched)
            t3_kws = ", ".join(r.tier3_keywords_matched)
            lines.append(
                f"| {orig_short} | `{r.proposed_slug[:50]}` | {r.domain} ({d_kws}) | **{t3_kws}** | `{r.recommended_mode}` |"
            )
        lines.append("")

    # ---- Detail by domain ----
    lines.append("## Detail by Domain")
    lines.append("")
    by_dom: dict[str, list[tuple]] = {}
    for r, c in enriched:
        by_dom.setdefault(r.domain, []).append((r, c))
    for domain in sorted(by_dom.keys()):
        entries = by_dom[domain]
        lines.append(f"### {domain} ({len(entries)})")
        lines.append("")
        lines.append("| Confidence | Mode | Domain kws | TIER 3 kws | Proposed slug | Original |")
        lines.append("|---|---|---|---|---|---|")
        for r, conf in entries:
            orig_short = r.original_filename[:45] + ("..." if len(r.original_filename) > 45 else "")
            d_kws = ", ".join(r.domain_keywords_matched) or "—"
            t3_kws = ", ".join(r.tier3_keywords_matched) or "—"
            lines.append(
                f"| {conf} | `{r.recommended_mode}` | {d_kws} | {t3_kws} | `{r.proposed_slug[:55]}` | {orig_short} |"
            )
        lines.append("")

    # ---- Recommendation summary ----
    lines.append("## Recommendation (Stage 25 review)")
    lines.append("")
    lines.append(f"- **High confidence**: {by_conf.get('HIGH', 0)}건 — sample apply 후보 (위 Top 10 list)")
    lines.append(f"- **Medium-high**: {by_conf.get('MEDIUM-HIGH', 0)}건 — apply 가능, 사용자 검토 권장")
    lines.append(f"- **Medium**: {by_conf.get('MEDIUM', 0)}건 — apply 전 도메인 매칭 재확인")
    lines.append(f"- **Singleton weak**: {by_conf.get('MEDIUM (singleton, weak)', 0)}건 — TIER 2 강등 검토")
    lines.append(f"- **Mis-classification 의심**: {len(review_needed)}건 — 수동 결정 (보통 TIER 3 로 강등)")
    lines.append("")
    lines.append("**진행 제안**:")
    lines.append("1. Top 10 HIGH 만 `--apply-hygiene` 으로 sample 실행 → rename + meta.yml 결과 검증")
    lines.append("2. 검증 통과 시 전체 TIER 1 (45건) `--apply-hygiene` 실행")
    lines.append("3. TIER 2/3 은 별도 stage 에서 처리 (현재는 TIER 1 검증이 우선)")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    OUT_MD.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Review → {OUT_MD.relative_to(ROOT)}")
    print()
    print(f"  HIGH:                       {by_conf.get('HIGH', 0)}")
    print(f"  MEDIUM-HIGH:                {by_conf.get('MEDIUM-HIGH', 0)}")
    print(f"  MEDIUM:                     {by_conf.get('MEDIUM', 0)}")
    print(f"  MEDIUM (singleton, weak):   {by_conf.get('MEDIUM (singleton, weak)', 0)}")
    print(f"  REVIEW (TIER 3 overlap):    {len(review_needed)}")


if __name__ == "__main__":
    main()
